### PR TITLE
Fixes #42: Disable Call Stack Navigation Buttons

### LINKED ISSUE #42: Orbit crashes when switching call stacks before capturing
If you launch Orbit, click on the sampling tab and try to switch the CallStack ("<" or ">") the App just crashes. If there are no call stacks available, the buttons should be not clickable.

### PR DESCRIPTION
**Pull request by florian-kuebler**
Disables the call stack navigation buttons, if either there is no capture yet, or if no symbols are selected for which the call stacks should be shown.
This fixes #42

### CODE REVIEW

**Comment by florian-kuebler** [comment]
The two buttons could also just get disabled in the QtCreator by default. Then we would not need to disable them in the OrbitSamplingReport constructor. However, doing this with my version of QtCreator changed all the generated files, which is why I omitted doing this.

File: OrbitGl/SamplingReport.h [hunk 1]
```diff
@@ -25,14 +25,14 @@ class SamplingReport
     void DecrementCallstackIndex();
     std::wstring GetSelectedCallstackString();
     void SetUiRefreshFunc( std::function<void()> a_Func ){ m_UiRefreshFunc = a_Func; }
+    std::shared_ptr< struct SortedCallstackReport >     m_SelectedSortedCallstackReport;
```
Comment (pierricgimmig) [inline OrbitGl/SamplingReport.h]: Let's add a getter method instead, perhaps a 'bool HasCallstacks() const' since it seems we only care about whether the presence of callstacks?

Comment (florian-kuebler) [reply OrbitGl/SamplingReport.h]: Addressed the issue. We are now using a HasCallstacks method.
